#
# ███╗   ██╗██╗ ██████╗██╗  ██╗██╗      █████╗ ███████╗███╗   ███╗ █████╗ ████████╗███████╗██╗   ██╗██╗     ██╗      █████╗    ██████╗ ███████╗
# ████╗  ██║██║██╔════╝██║ ██╔╝██║     ██╔══██╗██╔════╝████╗ ████║██╔══██╗╚══██╔══╝╚══███╔╝██║   ██║██║     ██║     ██╔══██╗   ██╔══██╗██╔════╝
# ██╔██╗ ██║██║██║     █████╔╝ ██║     ███████║███████╗██╔████╔██║███████║   ██║     ███╔╝ ██║   ██║██║     ██║     ███████║   ██║  ██║█████╗
# ██║╚██╗██║██║██║     ██╔═██╗ ██║     ██╔══██║╚════██║██║╚██╔╝██║██╔══██║   ██║    ███╔╝  ██║   ██║██║     ██║     ██╔══██║   ██║  ██║██╔══╝
# ██║ ╚████║██║╚██████╗██║  ██╗███████╗██║  ██║███████║██║ ╚═╝ ██║██║  ██║   ██║   ███████╗╚██████╔╝███████╗███████╗██║  ██║██╗██████╔╝███████╗
# ╚═╝  ╚═══╝╚═╝ ╚═════╝╚═╝  ╚═╝╚══════╝╚═╝  ╚═╝╚══════╝╚═╝     ╚═╝╚═╝  ╚═╝   ╚═╝   ╚══════╝ ╚═════╝ ╚══════╝╚══════╝╚═╝  ╚═╝╚═╝╚═════╝ ╚══════╝
#
# Copyright 2024 Nicklas Matzulla
# ForestAttack v1.2.0
#

mariadb:
  host: "localhost"
  port: 3306
  user: "forestattack"
  pass: "forestattack"
  db: "forestattack"
  useSSL: false
  maxPoolSize: 8