#
# ███╗   ██╗██╗ ██████╗██╗  ██╗██╗      █████╗ ███████╗███╗   ███╗ █████╗ ████████╗███████╗██╗   ██╗██╗     ██╗      █████╗    ██████╗ ███████╗
# ████╗  ██║██║██╔════╝██║ ██╔╝██║     ██╔══██╗██╔════╝████╗ ████║██╔══██╗╚══██╔══╝╚══███╔╝██║   ██║██║     ██║     ██╔══██╗   ██╔══██╗██╔════╝
# ██╔██╗ ██║██║██║     █████╔╝ ██║     ███████║███████╗██╔████╔██║███████║   ██║     ███╔╝ ██║   ██║██║     ██║     ███████║   ██║  ██║█████╗
# ██║╚██╗██║██║██║     ██╔═██╗ ██║     ██╔══██║╚════██║██║╚██╔╝██║██╔══██║   ██║    ███╔╝  ██║   ██║██║     ██║     ██╔══██║   ██║  ██║██╔══╝
# ██║ ╚████║██║╚██████╗██║  ██╗███████╗██║  ██║███████║██║ ╚═╝ ██║██║  ██║   ██║   ███████╗╚██████╔╝███████╗███████╗██║  ██║██╗██████╔╝███████╗
# ╚═╝  ╚═══╝╚═╝ ╚═════╝╚═╝  ╚═╝╚══════╝╚═╝  ╚═╝╚══════╝╚═╝     ╚═╝╚═╝  ╚═╝   ╚═╝   ╚══════╝ ╚═════╝ ╚══════╝╚══════╝╚═╝  ╚═╝╚═╝╚═════╝ ╚══════╝
#
# Copyright 2024 Nicklas Matzulla
# ForestAttack v1.0.0-SNAPSHOT
#

spawn:
  spawnPosition:
    world: "world"
    x: -228.5
    y: 208.0
    z: -8.5
    yaw: 180
    pitch: 0
  protection:
    min:
      world: "world"
      x: -328
      y: -65
      z: 92
    max:
      world: "world"
      x: -128
      y: 320
      z: -108
shop:
  spawnPosition:
    world: "world"
    x: -3841.5
    y: 63.0
    z: -3319.5
    yaw: 0
    pitch: 0
  protection:
    min:
      world: "world"
      x: -3950
      y: -64
      z: -3050
    max:
      world: "world"
      x: -3675
      y: 320
      z: -3180