#
# ███╗   ██╗██╗ ██████╗██╗  ██╗██╗      █████╗ ███████╗███╗   ███╗ █████╗ ████████╗███████╗██╗   ██╗██╗     ██╗      █████╗    ██████╗ ███████╗
# ████╗  ██║██║██╔════╝██║ ██╔╝██║     ██╔══██╗██╔════╝████╗ ████║██╔══██╗╚══██╔══╝╚══███╔╝██║   ██║██║     ██║     ██╔══██╗   ██╔══██╗██╔════╝
# ██╔██╗ ██║██║██║     █████╔╝ ██║     ███████║███████╗██╔████╔██║███████║   ██║     ███╔╝ ██║   ██║██║     ██║     ███████║   ██║  ██║█████╗
# ██║╚██╗██║██║██║     ██╔═██╗ ██║     ██╔══██║╚════██║██║╚██╔╝██║██╔══██║   ██║    ███╔╝  ██║   ██║██║     ██║     ██╔══██║   ██║  ██║██╔══╝
# ██║ ╚████║██║╚██████╗██║  ██╗███████╗██║  ██║███████║██║ ╚═╝ ██║██║  ██║   ██║   ███████╗╚██████╔╝███████╗███████╗██║  ██║██╗██████╔╝███████╗
# ╚═╝  ╚═══╝╚═╝ ╚═════╝╚═╝  ╚═╝╚══════╝╚═╝  ╚═╝╚══════╝╚═╝     ╚═╝╚═╝  ╚═╝   ╚═╝   ╚══════╝ ╚═════╝ ╚══════╝╚══════╝╚═╝  ╚═╝╚═╝╚═════╝ ╚══════╝
#
# Copyright 2024 Nicklas Matzulla
# ForestAttack v1.0.0-SNAPSHOT
#

#
# In this configuration, messages can be configured.
# The MiniMessage format is supported in the entire configuration.
# MiniMessage documentation: https://docs.advntr.dev/minimessage/format.html
#

general:
  prefix: "<dark_gray>»</dark_gray> <yellow>ForestAttack</yellow> <dark_gray>|</dark_gray> "
  onlyPlayers: "Nur <red>Spieler</red> können diesen <red>Befehl ausführen</red>!"
  playerNotFound: "Der <red>Spieler</red> kann <red>nicht gefunden</red> werden."
  unsupportedOperation: "Diese <red>Aktion</red> ist derzeit <red>nicht unterstützt</red>!"
  patterns:
    enabled: "<green>aktiviert</green>"
    disabled: "<red>deaktiviert</red>"
  kickMessage:
    - "<dark_gray><st>■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■</st></dark_gray>"
    - ""
    - "Die <red>Verbindung zum Server</red> wurde <red>unterbrochen</red>."
    - "Fehler <dark_gray>|</dark_gray> <kick_reason>"
    - ""
    - "<dark_gray><st>■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■</st></dark_gray>"
    - ""

errors:
  kick:
    failedLoadData: "<red>Daten können nicht geladen werden</red>"

features:
  chat:
    joinMessage: "<name_colored> hat den <green>Server betreten</green>."
    quitMessage: "<name_colored> hat den <red>Server verlassen</red>."
    chatFormat: "<dark_gray>»</dark_gray> <name_prefixed_and_colored> <dark_gray>|</dark_gray> <message>"
    header:
      - "<dark_gray>   <st>■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■</st>   </dark_gray>"
      - ""
      - "<gradient:#1b457e:#dd3c1b><b>ForestAttack IV</b></gradient>"
      - "Viel Spaß beim spielen!"
      - ""
    footer:
      - ""
      - "Online <dark_gray>| <green><online_players></green>/<red><max_players></red></dark_gray>"
      - ""
      - "<dark_gray>   <st>■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■</st>   </dark_gray>"
    vanishedNameTagColor: "YELLOW"
    vanishedSuffix: " <dark_gray>[<yellow>V</yellow>]</dark_gray>"

commands:
  biome: "Dein aktuelles <green>Biom</green> lautet <biome_name_translated>."
  chunkBorders:
    enabled: "Du hast die <green>Chunkgrenzen aktiviert</green>."
    disabled: "Du hast die <red>Chunkgrenzen deaktiviert</red>."
  enderchest:
    openedSelf: "Du hast deine Enderchest <green>geöffnet</green>."
    openedOther: "Du hast die <green>Enderchest</green> von <victim_name_colored> <green>geöffnet</green>."
    failed: "Die <red>Enderchest</red> von <victim_name_colored> konnte <red>nicht geöffnet</red> werden."
    # Prefixes and colors of offline players are not loaded for performance reasons.
    offlinePlayerTitle: "<dark_gray><lang:container.enderchest> |</dark_gray> <red>Offline</red>"
  shop:
    disabled: "Der <red>Shop</red> ist <red>derzeit deaktiviert</red>!"
    updateStatus: "Du hast den Shop <status>."
    usage: "Nutze <dark_gray>➥ /<aqua>shop</aqua> <<aqua>enable</aqua>/<aqua>disable</aqua>>"
  kit:
    claimed: "Du hast dein <green>Starterkit erfolgreich abgeholt</green>."
    alreadyClaimed: "Du hast dein <red>Starterkit bereits abgeholt</red>."