#
# ███╗   ██╗██╗ ██████╗██╗  ██╗██╗      █████╗ ███████╗███╗   ███╗ █████╗ ████████╗███████╗██╗   ██╗██╗     ██╗      █████╗    ██████╗ ███████╗
# ████╗  ██║██║██╔════╝██║ ██╔╝██║     ██╔══██╗██╔════╝████╗ ████║██╔══██╗╚══██╔══╝╚══███╔╝██║   ██║██║     ██║     ██╔══██╗   ██╔══██╗██╔════╝
# ██╔██╗ ██║██║██║     █████╔╝ ██║     ███████║███████╗██╔████╔██║███████║   ██║     ███╔╝ ██║   ██║██║     ██║     ███████║   ██║  ██║█████╗
# ██║╚██╗██║██║██║     ██╔═██╗ ██║     ██╔══██║╚════██║██║╚██╔╝██║██╔══██║   ██║    ███╔╝  ██║   ██║██║     ██║     ██╔══██║   ██║  ██║██╔══╝
# ██║ ╚████║██║╚██████╗██║  ██╗███████╗██║  ██║███████║██║ ╚═╝ ██║██║  ██║   ██║   ███████╗╚██████╔╝███████╗███████╗██║  ██║██╗██████╔╝███████╗
# ╚═╝  ╚═══╝╚═╝ ╚═════╝╚═╝  ╚═╝╚══════╝╚═╝  ╚═╝╚══════╝╚═╝     ╚═╝╚═╝  ╚═╝   ╚═╝   ╚══════╝ ╚═════╝ ╚══════╝╚══════╝╚═╝  ╚═╝╚═╝╚═════╝ ╚══════╝
#
# Copyright 2024 Nicklas Matzulla
# ForestAttack v1.2.0
#

commands:
  spawn:
    enabled: true
  shop:
    enabled: true
  kit:
    items:
      - "STONE_SWORD:1"
      - "STONE_PICKAXE:1"
      - "STONE_AXE:1"
      - "STONE_SHOVEL:1"
      - "LEATHER_CHESTPLATE:1"
      - "LEATHER_LEGGINGS:1"
      - "BAKED_POTATO:32"
