#
# ███╗   ██╗██╗ ██████╗██╗  ██╗██╗      █████╗ ███████╗███╗   ███╗ █████╗ ████████╗███████╗██╗   ██╗██╗     ██╗      █████╗    ██████╗ ███████╗
# ████╗  ██║██║██╔════╝██║ ██╔╝██║     ██╔══██╗██╔════╝████╗ ████║██╔══██╗╚══██╔══╝╚══███╔╝██║   ██║██║     ██║     ██╔══██╗   ██╔══██╗██╔════╝
# ██╔██╗ ██║██║██║     █████╔╝ ██║     ███████║███████╗██╔████╔██║███████║   ██║     ███╔╝ ██║   ██║██║     ██║     ███████║   ██║  ██║█████╗
# ██║╚██╗██║██║██║     ██╔═██╗ ██║     ██╔══██║╚════██║██║╚██╔╝██║██╔══██║   ██║    ███╔╝  ██║   ██║██║     ██║     ██╔══██║   ██║  ██║██╔══╝
# ██║ ╚████║██║╚██████╗██║  ██╗███████╗██║  ██║███████║██║ ╚═╝ ██║██║  ██║   ██║   ███████╗╚██████╔╝███████╗███████╗██║  ██║██╗██████╔╝███████╗
# ╚═╝  ╚═══╝╚═╝ ╚═════╝╚═╝  ╚═╝╚══════╝╚═╝  ╚═╝╚══════╝╚═╝     ╚═╝╚═╝  ╚═╝   ╚═╝   ╚══════╝ ╚═════╝ ╚══════╝╚══════╝╚═╝  ╚═╝╚═╝╚═════╝ ╚══════╝
#
# Copyright 2024 Nicklas Matzulla
# ForestAttack v1.0.0-SNAPSHOT
#

commands:
  shop:
    enabled: true